baseURL = "https://hanmei765-max.github.io/"
title = "嵌入式技术总结"
theme = "stack"

# 默认语言
defaultContentLanguage = "zh-cn"

[params]
  author = "hanmei765-max"
  description = "记录嵌入式Linux、驱动开发与RTOS学习笔记"

[permalinks]
  post = "/p/:slug/"
  page = "/:slug/"

